git_package = Package("git")

dotfiles = Git("https://github.com/jared-skinner/dotfiles.git")
df_path = dotfiles.target

zsh = Package("zsh")
fzf = Package("fzf")
rg = Package("ripgrep")
htop = Package("htop")
rust = Package("rust")
go = Package("go")
terminal = Package("alacritty")
npm = Package("npm")
bat = Package("bat")

packages = Group(name = "packages", deps = [
  zsh,
  fzf,
  rg,
  htop,
  rust,
  go,
  terminal,
  npm,
  bat
])

copy_dots = Group(name = "copy_dots", deps = [
    Copy(
        src = os.path.join(df_path, ".gitconfig"),
        dest = "~/.gitconfig",
        deps = [git_package, dotfiles]
    ),
    Copy(
        src=os.path.join(df_path, "nvim"),
        dest=os.path.join("~", ".config", "nvim"),
        deps=[fzf, rg, dotfiles]
    ),
    Copy(
        src=os.path.join(df_path, "tmux"),
        dest=os.path.join("~", ".tmux"),
        deps=[Package("tmux"), dotfiles]
    ),
    Copy(
        src=os.path.join(df_path, "zsh"),
        dest=os.path.join("~", ".zsh"),
        deps=[zsh, dotfiles]
    )
])

main_task = Main(name="work", deps=[
  copy_dots,
  packages
])

main_task.run()
